all: FirewallTestClient.class FirewallTestServer.class

FirewallTestClient.class: FirewallTestClient.java
	javac FirewallTestClient.java

FirewallTestServer.class: FirewallTestServer.java
	javac FirewallTestServer.java

clean:
	rm -f *.class
