#!/bin/bash

if [ -z "$1" ]; then
  echo "You have to provide param --  x for appKey=xx"
  exit 1	
fi

APP_KEY=$1$1
CLI_PORT=1010$1
TOMP2P_PORT=1030$1

BOOTSTRAP_ADDRESS=193.0.109.30
BOOTSTRAP_TOMP2P_PORT=10301
BOOTSTRAP_PORT=10201

export COMMON_ARGS="--CLASS_NAME=org.nebulostore.gui.GUIController --BOOTSTRAP_ADDRESS=$BOOTSTRAP_ADDRESS --BOOTSTRAP_TOMP2P_PORT=$BOOTSTRAP_TOMP2P_PORT --BOOTSTRAP_PORT=$BOOTSTRAP_PORT --APP_KEY=$APP_KEY --BOOTSTRAP_MODE=client --CLI_PORT=$CLI_PORT --TOMP2P_PORT=$TOMP2P_PORT --BDB_TYPE=proxy"

./scripts/_build-production.sh
